/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Msg_to`;

DROP TABLE IF EXISTS `Msg`;

DROP TABLE IF EXISTS `Group_members`;

DROP TABLE IF EXISTS `Group`;

DROP TABLE IF EXISTS `RelationNetwork`;

DROP TABLE IF EXISTS `Member`;

CREATE TABLE IF NOT EXISTS `schema_version` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY,
  `version` BIGINT UNSIGNED NOT NULL,
  `migration` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

DELETE FROM `schema_version`
  WHERE `name` = '';

CREATE TABLE `Member` (
  `name` TEXT NOT NULL,
  `pwd` TEXT NOT NULL,
  `ip` TEXT NOT NULL,
  `port` SMALLINT UNSIGNED NOT NULL,
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT)
 ENGINE=InnoDB;

CREATE TABLE `RelationNetwork` (
  `x` BIGINT UNSIGNED NULL,
  `y` BIGINT UNSIGNED NULL,
  `w` SMALLINT NOT NULL,
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
  /*
  CONSTRAINT `RelationNetwork_x_fk`
    FOREIGN KEY (`x`)
    REFERENCES `Member` (`id`)
  */
  /*
  CONSTRAINT `RelationNetwork_y_fk`
    FOREIGN KEY (`y`)
    REFERENCES `Member` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Group` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL)
 ENGINE=InnoDB;

CREATE TABLE `Group_members` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NOT NULL,
  CONSTRAINT `Group_members_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Group` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Group_members_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Member` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Group_members` (`object_id`);

CREATE INDEX `index_i`
  ON `Group_members` (`index`);

CREATE TABLE `Msg` (
  `from` BIGINT UNSIGNED NULL,
  `content` TEXT NOT NULL,
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT
  /*
  CONSTRAINT `Msg_from_fk`
    FOREIGN KEY (`from`)
    REFERENCES `Member` (`id`)
  */)
 ENGINE=InnoDB;

CREATE TABLE `Msg_to` (
  `object_id` BIGINT UNSIGNED NOT NULL,
  `index` BIGINT UNSIGNED NOT NULL,
  `value` BIGINT UNSIGNED NULL,
  CONSTRAINT `Msg_to_object_id_fk`
    FOREIGN KEY (`object_id`)
    REFERENCES `Msg` (`id`)
    ON DELETE CASCADE
  /*
  CONSTRAINT `Msg_to_value_fk`
    FOREIGN KEY (`value`)
    REFERENCES `Member` (`id`)
  */)
 ENGINE=InnoDB;

CREATE INDEX `object_id_i`
  ON `Msg_to` (`object_id`);

CREATE INDEX `index_i`
  ON `Msg_to` (`index`);

INSERT IGNORE INTO `schema_version` (
  `name`, `version`, `migration`)
  VALUES ('', 1, 0);

